import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navabar from "@/components/Navabar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 


{
  return (
    <html lang="en">
      <body className={inter.className}>
       <Navabar></Navabar>
       <div className="flex justify-center w-full items-center flex-col mt-24 gap-6"> 
        {children}</div></body>
   
    </html>
  );
}
